<?php 

$this->headTitle($this->book->getTitle());
$this->headTitle($this->page->getTitle());

if (! $this->contentOnly) {
    $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js')
                       ->appendFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js')
                       ->appendFile($this->baseUrl . '/js/jquery.treeview.min.js')
                       ->appendScript(<<<EOJS
$(document).ready(function() {
    $("#toc-sidebar ul.toc").treeview({
        collapsed: true,
        animated: "medium",
        persist: "location"
    });
});
EOJS
                        );

    $this->headLink()->appendStylesheet($this->baseUrl . '/css/jquery.treeview.css');
}

?>
<?php if (! $this->contentOnly): ?>
    <div id="toc-sidebar">
        <h3>Table of Contents</h3>
        <?php echo $this->tableOfContents($this->book, $this->page)?>
    </div>
<?php endif; ?>
    
    <div id="content"<?php if (! $this->contentOnly) echo ' class="has-sidebar"'; ?>>
        <?php echo $this->page->getContent(); ?>
    
<?php if (! $this->contentOnly): ?>    
        <div id="comments">
            <h2>User Comments</h2>
            <div id="user-comments">
                <?php echo $this->userComments($this->page); ?>            
            </div>

            <div id="post-comment">
                <h3>Post a Comment</h3>
<?php if ($this->commentsAreModerated): ?>
                <p>Please note: comments are moderated</p>
<?php endif; ?>
                <?php echo $this->commentForm; ?>
            </div>
        </div>
<?php endif; ?>
    </div>